# Generated by Django 5.2.7 on 2025-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField()),
                ('car_colour', models.CharField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
